version: 0.2

phases:
    install:
        commands:
            - 'apt-get update'
			- 'apt-get install -y git'
  pre_build:
    commands:
	  - echo ......git version..........
	  - git --version
      - echo Nothing to do in the pre_build phase...
      - ls -ltr
      - chmod 755 invoke.sh
      - ls -ltr
      - /bin/bash invoke.sh 
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
